version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: todolist_mysql
    environment:
      MYSQL_ROOT_PASSWORD: daw12
      MYSQL_DATABASE: toDoList
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      todolist_network: {}

  backend:
    build: ./backend
    container_name: todolist_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: daw12
      DB_NAME: toDoList
      PORT: 3000
      JWT_SECRET: mi_clave_super_secreta_12345
    ports:
      - "3000:3000"
    networks:
      todolist_network: {}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start

  frontend:
    build: ./frontend/todolistfront
    container_name: todolist_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      todolist_network: {}

networks:
  todolist_network:
    driver: bridge

volumes:
  db_data:
